// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAJTonWdR8dMNo1pidlplCtmPfOtmr8KK4',
    appId: '1:322819520755:web:557c3a4fd8afd47c861f86',
    messagingSenderId: '322819520755',
    projectId: 'saad-flutter-project',
    authDomain: 'saad-flutter-project.firebaseapp.com',
    storageBucket: 'saad-flutter-project.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDHG3A_vOYnwhWBXlYP6l2jUCnhhWeltbI',
    appId: '1:322819520755:android:722ed16191518d11861f86',
    messagingSenderId: '322819520755',
    projectId: 'saad-flutter-project',
    storageBucket: 'saad-flutter-project.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAYy3uIQbXBvPqgB1CGIahOzQmZYdAFanE',
    appId: '1:322819520755:ios:359ed30e91674da4861f86',
    messagingSenderId: '322819520755',
    projectId: 'saad-flutter-project',
    storageBucket: 'saad-flutter-project.appspot.com',
    iosBundleId: 'com.example.ecommerceapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAYy3uIQbXBvPqgB1CGIahOzQmZYdAFanE',
    appId: '1:322819520755:ios:325b55800a362cb6861f86',
    messagingSenderId: '322819520755',
    projectId: 'saad-flutter-project',
    storageBucket: 'saad-flutter-project.appspot.com',
    iosBundleId: 'com.example.ecommerceapp.RunnerTests',
  );
}
